# ============================================================
# Deploy Flask Backend (in /backend folder) to Azure App Service
# ============================================================

name: Build and deploy Python Flask app to Azure Web App - ai-product-backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Archive backend for deployment
        run: |
          cd backend
          zip -r ../backend.zip .

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: backend
          path: backend.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: backend

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4C5FA6D8D0774B739B9A44D77C0D9F6C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9DFE45392DF14B7394F085813D7C4B19 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C01AB3DC72904E75AB7DD70D490E5BF6 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ai-product-backend'
          slot-name: 'Production'
          package: backend.zip
